default:
  image: python:3.14-slim 

stages:          # l'ordre des étapes du pipeline
  - lint
  - test

.python-setup: &python-setup     # job "caché" (le point devant = template, non exécuté)
  before_script:
    - cd services/products-api
    - pip install -r requirements-dev.txt

lint-job:                          # un nom de job, libre
  stage: lint                      # à quelle étape il appartient        # le conteneur dans lequel il s'exécute
  <<: *python-setup   
  script:                          # les commandes, comme dans ton terminal
    - ruff check app/

test-job:
  stage: test
  <<: *python-setup   
  script:
    - python -m pytest