name: products-api
namespace: ncap
image:
  repository: registry.gitlab.com/teakt/ncap
  tag: 5881b7a0
imagePullSecret: gitlab-registry
port: 8000
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
autoscaling:
  min: 1
  max: 3
  targetCPU: 70
kong:
  keyauth: products-api-key-auth
  namespace: kong
  ratelimiting: products-api-rate-limiting
