FROM python:3.14-slim

WORKDIR /code

COPY requirements.txt  ./

RUN pip install -r requirements.txt --no-cache-dir

COPY app/ ./app

RUN adduser --disabled-password --gecos "" appuser

USER appuser

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
